import React,{useRef,useState} from 'react';
import {stamp} from './view.mjs';
const labels={queries:'Поисковые запросы',selection:'Подбор товаров',schedule:'Расписание',learning:'Эксперименты обучения'};
function describe(scope,v){if(scope==='schedule')return `${v.mode==='interval'?'Каждые '+v.post_interval_minutes+' минут':v.post_times.join(', ')} · ${v.timezone} · ${v.paused?'пауза':v.enabled?'включено':'выключено'} · поиск ${v.search_interval_minutes} мин`;if(scope==='queries')return v.filter(r=>!r.archived).map(r=>r.text+(r.enabled?'':' (выкл.)')).join('; ');if(scope==='selection')return `Цена ${v.settings.min_price}–${v.settings.max_price||'без лимита'} ₽ · рейтинг от ${v.settings.min_rating} · отзывы от ${v.settings.min_feedbacks} · ${v.active?'свои правила':'Legacy'}`;if(scope==='learning')return `Эксперименты ${v.exploration_percent??0}% · SHADOW`;return 'Настройки';}
export function ConfigHistory({client,zone,scope,onRestored,disabled}){
  const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');const lock=useRef(false);
  async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
  async function load(cursor){const r=await client.api('/api/admin/config/history'+(cursor?'?cursor='+cursor:''));setData(cursor?{...r,items:[...data.items,...r.items]}:r);}
  async function restore(v){if(!window.confirm('Восстановить «'+labels[v.scope]+'» до этого изменения? Это станет новой записью в журнале.'))return;const path={queries:'search',selection:'selection',schedule:'schedule',learning:'learning'}[v.scope];if(!path)throw Error('Восстановление этого раздела пока недоступно');const current=await client.api('/api/admin/'+path);await client.api('/api/admin/config/restore','POST',{id:v.id,revision:current.revision});await load();await onRestored?.();setDone('Настройки восстановлены. История сохранена.');}
  return <div className="panel"><h2>История настроек</h2><p>Последние 100 изменений. Восстановление проверяется сервером и записывается как новое изменение.</p><button className="control-button" disabled={busy||disabled} onClick={()=>run(()=>load())}>Показать журнал</button>{error&&<p role="alert" className="notice red">{error}</p>}{done&&<p role="status" className="notice green">{done}</p>}{data?.items.filter(v=>!scope||v.scope===scope).map(v=><article className="observation" key={v.id}><strong>{labels[v.scope]||'Настройки'} · {stamp(v.ts,zone)}</strong><p>До: {describe(v.scope,v.before)}</p><p>После: {describe(v.scope,v.after)}</p><button className="control-button" disabled={busy||disabled} onClick={()=>run(()=>restore(v))}>Восстановить «до»</button></article>)}{data&&!data.items.length&&<p>Изменений пока нет.</p>}{data?.next_cursor&&<button className="control-button" disabled={busy} onClick={()=>run(()=>load(data.next_cursor))}>Более ранние изменения</button>}</div>;
}
