import React,{useEffect,useRef,useState} from 'react';
import {stamp} from './view.mjs';
const origins={existing:'Из действующей настройки · происхождение ранее не записано',manual:'Добавлен вручную',algorithm:'Предложен алгоритмом'};
const count=n=>n==null?'Нет данных':n.toLocaleString('ru-RU');
export function QueryManager({client,zone,onDirty}){
  const [data,setData]=useState(null),[draft,setDraft]=useState([]),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[filter,setFilter]=useState(''),[archived,setArchived]=useState(false),[history,setHistory]=useState(null),[historyId,setHistoryId]=useState(''),[newText,setNewText]=useState(''),[newOrigin,setNewOrigin]=useState('manual'),[versions,setVersions]=useState(null),[suggestions,setSuggestions]=useState(null);
  const lock=useRef(false),alive=useRef(true),testIds=useRef(new Map());
  async function load(){const r=await client.api('/api/admin/search');if(alive.current){setData(r);setDraft(r.queries);setDirty(false);onDirty(false);}return r;}
  useEffect(()=>{alive.current=true;load().catch(e=>setError(e.message));return()=>{alive.current=false;};},[]);
  function edit(rows){setDraft(rows);setDirty(true);onDirty(true);setMessage('');}
  const change=(id,patch)=>edit(draft.map(r=>r.id===id?{...r,...patch}:r));
  async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}}
  async function save(){await client.api('/api/admin/search/queries','PUT',{revision:data.revision,queries:draft});await load();setMessage('Список сохранён. Поиск будет использовать эти фразы и приоритеты.');}
  async function showHistory(id='',cursor){const r=await client.api('/api/admin/search/history?query_id='+encodeURIComponent(id)+(cursor?'&cursor='+cursor:''));setHistoryId(id);setHistory(cursor?{...r,items:[...history.items,...r.items]}:r);}
  async function test(r){let id=testIds.current.get(r.id);if(!id){id=crypto.randomUUID();testIds.current.set(r.id,id);}await client.api('/api/admin/search/test','POST',{query_id:r.id,request_id:id});testIds.current.delete(r.id);await load();setMessage('Проверка поставлена в очередь. Товары не попадут в публикации. Результат появится в истории после обработки.');}
  function exportFile(){const safe={version:1,queries:data.queries.map(({id,text,enabled,archived,priority,origin})=>({id,text,enabled,archived,priority,origin}))};const url=URL.createObjectURL(new Blob([JSON.stringify(safe,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='wb-search-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function importFile(file){if(!file)return;if(file.size>64000)throw new Error('Файл должен быть меньше 64 КБ');const v=JSON.parse(await file.text());if(v.version!==1||!Array.isArray(v.queries)||v.queries.length>100||v.queries.some(r=>typeof r?.text!=='string'||typeof r.enabled!=='boolean'||typeof r.archived!=='boolean'||!Number.isInteger(r.priority)))throw new Error('Это не файл настроек поисковых запросов');edit(v.queries.map(r=>({id:data.queries.find(x=>x.text===r.text)?.id||'new:'+crypto.randomUUID(),text:r.text,enabled:r.enabled,archived:r.archived,priority:r.priority,origin:'manual'})));setMessage('Файл загружен в предпросмотр. Проверьте фразы и нажмите «Сохранить запросы».');}
  if(!data)return <section className="panel"><h2>Реальные поисковые запросы</h2><p>{error||'Читаем список из D1…'}</p>{error&&<button onClick={()=>run(load)}>Повторить</button>}</section>;
  const visible=draft.filter(r=>(archived||!r.archived)&&r.text.toLocaleLowerCase('ru').includes(filter.toLocaleLowerCase('ru'))),blocked=data.retry_at>Date.now()/1000||data.pending;
  return <section className="query-center" aria-busy={busy}>
    <div className="panel"><span className="eyebrow">Ваши фразы · реальные настройки D1</span><h2>🔍 Поиск товаров</h2><p>{data.queries.filter(r=>r.enabled&&!r.archived).length} активных · {data.queries.length} всего с архивом</p><p className="subtle">{data.stats_scope}</p>
      <label className="control-label">Найти фразу<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Название или часть запроса"/></label>
      <label className="toggle"><span>Показать архив</span><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/></label>
      <div className="product-actions"><button className="control-button" disabled={busy||dirty} onClick={()=>run(load)}>Обновить данные</button><button className="control-button" disabled={busy} onClick={()=>run(()=>showHistory())}>История поиска</button><button className="control-button" disabled={busy||dirty} onClick={exportFile}>Экспортировать</button><label className="file-button">Импортировать<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const f=e.target.files[0];e.target.value='';run(()=>importFile(f));}}/></label></div>
      {blocked&&<div className="notice yellow">{data.pending?'Одна проверка уже ожидает обработки.':'Следующая ручная проверка: '+stamp(data.retry_at,zone)}. Общая пауза WB — не менее 5 минут.</div>}
      {error&&<p role="alert" className="notice red">{error}</p>}{message&&<p role="status" className="notice green">{message}</p>}
    </div>
    {visible.map(r=><article className={'panel query-card '+(r.archived?'archived':'')} key={r.id}><div className="query-heading"><span className={'badge '+(r.enabled&&!r.archived?'green':'muted')}>{r.archived?'В архиве':r.enabled?'Активен':'Выключен'}</span><small>{origins[r.origin]||'Происхождение не записано'}</small></div><label className="control-label">Поисковая фраза<input aria-label={'Фраза '+r.text} value={r.text} maxLength={100} disabled={busy} onChange={e=>change(r.id,{text:e.target.value})}/></label>
      <div className="query-settings"><label className="toggle"><span>Использовать в поиске</span><input type="checkbox" disabled={busy||r.archived} checked={r.enabled&&!r.archived} onChange={e=>change(r.id,{enabled:e.target.checked})}/></label><label>Приоритет<select aria-label={'Приоритет '+r.text} disabled={busy} value={r.priority} onChange={e=>change(r.id,{priority:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} · {n===1?'обычный':n===5?'самый высокий':'повышенный'}</option>)}</select></label></div>
      <dl className="query-stats">{[['Найдено',r.stats?.found],['Новых артикулов',r.stats?.new_count],['Отобраны после фильтров',r.stats?.candidates],['Проверены цена и фото',r.stats?.passed],['В очередь',r.stats?.added],['Публикаций за 14 дней',r.published_14d],['Ошибок',r.stats?r.stats.runs-r.stats.successful:null]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{count(value)}</dd></div>)}</dl><p className="subtle">Последняя проверка: {r.stats?.last_used?stamp(r.stats.last_used,zone):'Нет данных'}</p>{r.stats?.last_error&&<p className="notice yellow">{r.stats.last_error==='WB HTTP 429'?'WB попросил сделать паузу.':r.stats.last_error==='WB HTTP 403'?'WB временно ограничил доступ.':'Последняя проверка не завершилась. Подробности в истории.'}</p>}
      <div className="product-actions"><button className="control-button primary" disabled={busy||dirty||blocked||r.archived} onClick={()=>run(()=>test(r))}>Проверить запрос</button><button className="control-button" disabled={busy} onClick={()=>run(()=>showHistory(r.id))}>Результаты и история</button><button className="control-button" disabled={busy} onClick={()=>change(r.id,{archived:!r.archived,enabled:false})}>{r.archived?'Вернуть из архива':'Убрать из активного списка'}</button></div>
    </article>)}
    <div className="panel"><h3>Добавить свой запрос</h3><button className="control-button" disabled={busy} onClick={()=>run(async()=>setSuggestions(await client.api('/api/admin/selection/suggestions')))}>Подсказать варианты</button>{suggestions&&<div><p>{suggestions.note}</p>{suggestions.items.map(v=><article className="observation" key={v.text}><strong>{v.text}</strong><p>{v.reason}</p><button className="control-button" onClick={()=>{setNewText(v.text);setNewOrigin('algorithm');}}>Выбрать фразу для добавления</button></article>)}{!suggestions.items.length&&<p>Пока нет новых вариантов.</p>}</div>}<label className="control-label">Новая фраза<input value={newText} maxLength={100} onChange={e=>{setNewText(e.target.value);setNewOrigin('manual');}} placeholder="Что искать для вашего канала"/></label><button className="control-button" disabled={busy||newText.trim().length<2||draft.length>=100} onClick={()=>{edit([...draft,{id:'new:'+crypto.randomUUID(),text:newText.trim(),priority:1,enabled:true,archived:false,origin:newOrigin}]);setNewText('');setNewOrigin('manual');}}>Добавить в список</button><div className="savebar"><button className="control-button primary" disabled={busy||!dirty} onClick={()=>run(save)}>Сохранить запросы</button>{dirty&&<button className="control-button" disabled={busy} onClick={()=>{setDraft(data.queries);setDirty(false);onDirty(false);setMessage('Изменения отменены.');}}>Отменить изменения</button>}<p>Редактирование пока только на экране. Сервер проверит весь список при сохранении.</p></div><button className="control-button" disabled={busy} onClick={()=>run(async()=>setVersions(await client.api('/api/admin/config/history')))}>Предыдущие настройки</button></div>
    {versions&&<div className="panel"><h3>Журнал изменений</h3>{versions.items.filter(v=>v.scope==='queries').map(v=><article className="observation" key={v.id}><strong>Поисковые фразы · {stamp(v.ts,zone)}</strong><p>{v.before.length} → {v.after.length} фраз, включая архив.</p><button className="control-button" disabled={busy||dirty} onClick={()=>{if(window.confirm('Восстановить список до этого изменения? Это будет новая запись в журнале.'))run(async()=>{await client.api('/api/admin/config/restore','POST',{id:v.id,revision:data.revision});await load();setVersions(null);setMessage('Предыдущий список восстановлен.');});}}>Восстановить предыдущий список</button></article>)}{!versions.items.length&&<p>Истории пока нет.</p>}</div>}
    {history&&<div className="panel"><h3>История реальных проверок</h3>{!history.items.length&&<p>Нет данных. Прошлые результаты не восстанавливаем из предположений.</p>}{history.items.map(h=><article className="observation" key={h.id}><strong>{h.query}</strong><p>{stamp(h.ts,zone)} · {h.origin==='manual_test'?'Ручная проверка без добавления':h.origin==='algorithm'?'Выбрано алгоритмом':'Автоматический поиск'}</p>{h.error?<p>Проверка прервана; действует общая пауза WB. Код: {h.error}</p>:<p>Найдено {h.receipt.found} · проверено {h.receipt.valid} · добавлено {h.receipt.added}</p>}{h.receipt.products?.map(p=><a key={p.id} className="search-result" href={p.url} target="_blank" rel="noopener noreferrer">{p.image&&<img src={p.image} alt="" loading="lazy"/>}<span>{p.title}<strong>{p.price} ₽</strong><small>Открыть Wildberries ↗</small></span></a>)}</article>)}{history.next_cursor&&<button className="control-button" disabled={busy} onClick={()=>run(()=>showHistory(historyId,history.next_cursor))}>Ещё проверки</button>}</div>}
  </section>;
}
