import React,{useEffect,useRef,useState} from 'react';
import {stamp} from './view.mjs';
export function QueueManager({client,zone,onRefresh,postPending}){
  const [filters,setFilters]=useState({view:'ready',q:'',category:'',query:'',readiness:'all'}),[applied,setApplied]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const lock=useRef(false);
  async function load(f=applied||filters,cursor){const r=await client.api('/api/admin/queue?'+new URLSearchParams({...f,...(cursor?{cursor}:{})}));setData(r);setApplied(f);}
  async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
  useEffect(()=>{run(()=>load());},[]);
  const change=(k,v)=>setFilters(x=>({...x,[k]:v})),button=(label,fn,disabled=false)=><button className="control-button" disabled={busy||disabled} onClick={()=>run(fn)}>{label}</button>;
  async function action(p,kind){if(kind==='post'&&!window.confirm('Опубликовать именно «'+p.title+'»? Повторно проверим цену, фото и дубли.'))return;if(kind==='delete'&&!window.confirm('Убрать товар из очереди? История и защита от дублей сохранятся.'))return;await client.action(kind,{pid:p.pid});setMessage(kind==='post'?'Заявка принята. Cron проверит этот товар; другой вместо него не отправится.':kind==='skip'?'Товар пропущен.':'Товар убран из очереди.');await load();await onRefresh();}
  return <section aria-busy={busy}><div className="panel"><h2>📦 Очередь и публикации</h2><label className="control-label">Что показать<select value={filters.view} onChange={e=>change('view',e.target.value)}><option value="ready">В очереди</option><option value="published">Опубликовано за 14 дней</option></select></label>{[['q','Название, бренд или артикул'],['category','Категория'],['query','Поисковая фраза']].map(([k,v])=><label className="control-label" key={k}>{v}<input maxLength={100} value={filters[k]} onChange={e=>change(k,e.target.value)}/></label>)}<label className="control-label">Готовность<select value={filters.readiness} onChange={e=>change('readiness',e.target.value)}><option value="all">Любая</option><option value="checked">Цена и фото проверены</option><option value="waiting">Ожидает проверки</option></select></label>{button('Применить фильтры',()=>load(filters))}<p className="subtle">{data?.note}</p>{error&&<p className="notice red" role="alert">{error}</p>}{message&&<p className="notice green" role="status">{message}</p>}</div>
    {!data?<p>Загружаем карточки…</p>:data.items.length?data.items.map(p=><article className="product-card" key={p.pid+':'+p.posted_at}><div className="product-summary">{p.image?<img src={p.image} alt="" loading="lazy" onError={e=>e.target.style.visibility='hidden'}/>:<div className="photo-empty">▦</div>}<div><span className="eyebrow">{p.category}</span><h2>{p.title}</h2><strong className="price">{p.price?.toLocaleString('ru-RU')} ₽</strong><small>⭐ {p.rating??'Нет данных'} · отзывов {p.feedbacks??'Нет данных'}</small><small>Артикул {p.pid}</small></div></div><p>Найден по запросу: {p.query||'Не записано'}</p><p>{p.reason}</p><span className={'badge '+(p.retry_at>Date.now()/1000?'yellow':'green')}>{p.readiness}</span><p>{p.posted_at?'Опубликован: ':'Последняя проверка: '}{stamp(p.posted_at||p.checked_at,zone)}</p><div className="product-actions">{data.view==='ready'&&<>{button('Опубликовать сейчас',()=>action(p,'post'),postPending)}{button('Пропустить',()=>action(p,'skip'))}{button('Удалить из очереди',()=>action(p,'delete'))}</>}<a href={p.url} target="_blank" rel="noreferrer">Открыть WB ↗</a></div></article>):<div className="panel"><h3>На этой странице совпадений нет</h3><p>{data.next_cursor?'Есть ещё карточки — перейдите дальше.':'Попробуйте ослабить фильтры или обновите очередь после поиска.'}</p></div>}
    <div className="actions">{button('В начало / обновить',()=>load())}{data?.next_cursor&&button('Следующая страница →',()=>load(applied,data.next_cursor))}</div></section>;
}
