import React,{useEffect,useRef,useState} from 'react';
const groups={clothes:'Одежда',shoes:'Обувь',accessories:'Аксессуары',other:'Другое'};
const lists={included_categories:'Включённые категории (пусто — все)',excluded_categories:'Исключённые категории',allowed_brands:'Разрешённые бренды (пусто — все)',excluded_brands:'Исключённые бренды',blocked_words:'Слова-исключения',blacklist:'Исключённые артикулы или части названия бренда'};
export function SelectionManager({client,onDirty}){
  const [data,setData]=useState(null),[draft,setDraft]=useState(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[pid,setPid]=useState(''),[similar,setSimilar]=useState(null),[versions,setVersions]=useState(null);const lock=useRef(false);
  async function load(){const r=await client.api('/api/admin/selection');setData(r);setDraft(r.settings);setDirty(false);onDirty(false);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  function edit(k,v){setDraft(x=>({...x,[k]:v}));setDirty(true);onDirty(true);setMessage('');}
  async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
  const button=(label,fn,disabled=false)=><button className="control-button" disabled={busy||disabled} onClick={()=>run(fn)}>{label}</button>;
  if(!draft)return <div className="panel">{error||'Загружаем действующий подбор…'}{error&&button('Повторить',load)}</div>;
  return <section aria-busy={busy}><div className="panel"><span className="eyebrow">Тема вашего канала</span><h2>🎯 Подбор товаров</h2><p>{data.note}</p>{!data.active&&<p className="notice muted">Расширенные правила ещё не сохранены. Работают прежние фильтры и порядок Legacy. Пример долей ниже не применяется.</p>}{error&&<p role="alert" className="notice red">{error}</p>}{message&&<p role="status" className="notice green">{message}</p>}
    <fieldset className="ui-controls" disabled={busy}>
      <div className="metrics">{Object.entries({min_price:'Цена от, ₽',max_price:'Цена до, ₽ (0 — без лимита)',min_rating:'Рейтинг от',min_feedbacks:'Число отзывов от'}).map(([k,label])=><label key={k} className="control-label">{label}<input type="number" min="0" step={k==='min_rating'?'.1':'1'} max={k==='min_rating'?5:10000000} value={draft[k]} onChange={e=>edit(k,Number(e.target.value))}/></label>)}</div>
      {Object.entries(lists).map(([k,label])=><label className="control-label" key={k}>{label}<textarea rows="2" value={Array.isArray(draft[k])?draft[k].join('\n'):draft[k]} onChange={e=>edit(k,e.target.value)} placeholder="Одно значение на строку"/></label>)}
      <h3>Аудитория</h3><p className="subtle">Если никто не выбран — любая. Определяем по словам в карточке, без предположений по фото.</p>{Object.entries({women:'Женщины',men:'Мужчины',children:'Дети',unisex:'Унисекс'}).map(([k,v])=><label className="toggle" key={k}><span>{v}</span><input type="checkbox" checked={draft.audiences.includes(k)} onChange={e=>edit('audiences',e.target.checked?[...draft.audiences,k]:draft.audiences.filter(x=>x!==k))}/></label>)}<label className="toggle"><span>Допускать неизвестную аудиторию</span><input type="checkbox" checked={draft.include_unknown_audience} onChange={e=>edit('include_unknown_audience',e.target.checked)}/></label>
      <div className="notice muted">Минимальная скидка недоступна: нет подтверждённой базовой цены. Стили, посадка и принты ожидают подключения проверенного Vision. Они не используются как выдуманные фильтры.</div>
      <h3>Разнообразие публикаций</h3><label className="toggle"><span>Использовать мои доли категорий</span><input type="checkbox" checked={draft.diversity_enabled} onChange={e=>edit('diversity_enabled',e.target.checked)}/></label><p className="subtle">Мягкая цель по последним 24 часам. При дефиците перераспределяем между доступными категориями. Жёсткие фильтры и защита от дублей сохраняются. River остаётся SHADOW.</p>
      <div className="metrics">{Object.entries(groups).map(([k,v])=><label className="control-label" key={k}>{v}, %<input disabled={!draft.diversity_enabled} type="number" min="0" max="100" value={draft.weights[k]} onChange={e=>edit('weights',{...draft.weights,[k]:Number(e.target.value)})}/></label>)}</div><p>Всего: {Object.values(draft.weights).reduce((a,b)=>a+b,0)}%</p>
      <label className="control-label">Желательный максимум одной группы подряд<input type="number" min="1" max="20" disabled={!draft.diversity_enabled} value={draft.max_consecutive} onChange={e=>edit('max_consecutive',Number(e.target.value))}/></label><label className="control-label">Избегать похожих среди последних N постов (0 — выключено)<input type="number" min="0" max="50" disabled={!draft.diversity_enabled} value={draft.similar_window} onChange={e=>edit('similar_window',Number(e.target.value))}/></label>
    </fieldset><div className="savebar">{button('Сохранить подбор',async()=>{const settings={...draft};for(const k of Object.keys(lists))if(typeof settings[k]==='string')settings[k]=settings[k].split('\n').map(x=>x.trim()).filter(Boolean);await client.api('/api/admin/selection','PUT',{revision:data.revision,settings});await load();setMessage('Подбор сохранён. Новые правила применяются к поиску и проверке очереди.');},!dirty)}{dirty&&button('Отменить изменения',load)}{button('Предыдущие настройки',async()=>setVersions((await client.api('/api/admin/config/history')).items.filter(r=>r.scope==='selection')),dirty)}</div>
      {versions&&<div><h3>Восстановление</h3>{!versions.length&&<p>Изменений ещё нет.</p>}{versions.map(v=><p key={v.id}>{new Date(v.ts*1000).toLocaleString('ru-RU')}{button('Вернуть настройки до изменения',async()=>{if(!window.confirm('Восстановить эту версию подбора?'))return;await client.api('/api/admin/config/restore','POST',{id:v.id,revision:data.revision});await load();setVersions(null);setMessage('Версия восстановлена и записана в журнал.');},dirty)}</p>)}</div>}
    </div><div className="panel"><h2>Похожие вещи</h2><p>Сравнение категории, названия, бренда, указанных размеров и количества в наборе. По фотографии сходство пока не оценивается.</p><label className="control-label">Артикул известного товара<input inputMode="numeric" value={pid} onChange={e=>setPid(e.target.value)}/></label>{button('Найти в очереди',async()=>setSimilar(await client.api('/api/admin/selection/similar?pid='+encodeURIComponent(pid))))}{similar&&<><p>{similar.scope}</p>{!similar.items.length&&<p>Подходящих совпадений в этой части очереди нет.</p>}{similar.items.map(p=><article className="observation" key={p.id}><a className="search-result" href={'https://www.wildberries.ru/catalog/'+p.id+'/detail.aspx'} target="_blank" rel="noreferrer"><img src={p.image} alt="" loading="lazy"/><span>{p.title}<small>{p.product||p.price} ₽ · совпадение текста {Math.round(p.score*100)}%</small></span></a><p>{p.reasons.join(' · ')}</p></article>)}</>}</div></section>;
}
