import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createHmac} from 'node:crypto';
import worker from './worker.mjs';
import {DEFAULT_SCHEDULE,validateSchedule} from './scheduler_api.mjs';
function environment(){const db=new DatabaseSync(':memory:'),wrap=(sql,args=[])=>({bind(...values){return wrap(sql,values);},async first(){return db.prepare(sql).get(...args)??null;},async all(){return {results:db.prepare(sql).all(...args)};},run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}});return {db,MINIAPP_BOT_TOKEN:'123:test',MINIAPP_ADMIN_ID:'11',MINIAPP_SYNC_KEY:'s'.repeat(40),DB:{prepare:wrap,async batch(statements){db.exec('BEGIN');try{const result=[];for(const s of statements)result.push(s.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}}};}
function signed(env,id){const fields={auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id})},check=Object.keys(fields).sort().map(k=>`${k}=${fields[k]}`).join('\n'),secret=createHmac('sha256','WebAppData').update(env.MINIAPP_BOT_TOKEN).digest();return new URLSearchParams({...fields,hash:createHmac('sha256',secret).update(check).digest('hex')}).toString();}
async function req(env,path,method='GET',body,identity='sync'){const headers={'Content-Type':'application/json'};if(identity==='sync')headers.Authorization='Bearer '+env.MINIAPP_SYNC_KEY;else if(identity)headers['X-Telegram-Init-Data']=signed(env,identity);const response=await worker.fetch(new Request('https://test.example/api/'+path,{method,headers,...(body?{body:JSON.stringify(body)}:{})}),env);return {status:response.status,...await response.json()};}
const runtime=(env,data)=>req(env,'scheduler/runtime','POST',data);

test('live driver and heartbeat determine Cron status, not old persisted ON flag',async()=>{const env=environment();await req(env,'scheduler/config');env.db.prepare("UPDATE scheduler_config SET status=?").run(JSON.stringify({cron_active:true,clock_heartbeat:Math.floor(Date.now()/1000)}));let c=await req(env,'scheduler/config');assert.equal(c.status.cron_active,false);assert.equal(c.status.driver,'github-actions');env.SCHEDULER_DRIVER='cloudflare-native';c=await req(env,'scheduler/config');assert.equal(c.status.cron_active,true);env.db.prepare("UPDATE scheduler_config SET status=?").run(JSON.stringify({clock_heartbeat:1}));assert.equal((await req(env,'scheduler/config')).status.cron_active,false);env.db.close();});
test('consuming clears only matching flag; stale clients cannot bypass server pause or caps',async()=>{
  const env=environment();
  await req(env,'scheduler/action','POST',{action:'search_now',request_id:'old'});
  await runtime(env,{op:'acquire',kind:'search',owner:'one'});
  await runtime(env,{op:'consume',kind:'search',owner:'one',request_id:'old'});
  assert.equal((await req(env,'scheduler/config')).search_request,null);
  await req(env,'scheduler/action','POST',{action:'search_now',request_id:'new'});
  await runtime(env,{op:'consume',kind:'search',owner:'one',request_id:'old'});
  assert.equal((await req(env,'scheduler/config')).search_request,'new');
  await runtime(env,{op:'acquire',kind:'post',owner:'one'});
  let config=await req(env,'scheduler/config');
  config=await req(env,'scheduler/config','PUT',{schedule:{...config.schedule,paused:true,max_posts_day:1},revision:config.revision});
  assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:9,max_day:288})).reason,'posting_paused');
  assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:9,max_day:288,request_id:'manual'})).ok,true);
  await runtime(env,{op:'complete',owner:'one',product_id:9,success:false});
  env.db.prepare('UPDATE scheduler_claims SET ts=?').run(Math.floor(Date.now()/1000)-400);
  assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:10,max_day:288,request_id:'manual2'})).ok,false);
  env.db.close();
});
test('schedule rejects invalid input and strips unrelated fields',()=>{assert.equal(validateSchedule({...DEFAULT_SCHEDULE,token:'do not save'}).token,undefined);assert.deepEqual(validateSchedule({...DEFAULT_SCHEDULE,post_times:['10:00','09:00','10:00']}).post_times,['09:00','10:00']);for(const bad of [{mode:'times'},{timezone:'bad/zone'},{weekdays:[]},{post_interval_minutes:4},{max_posts_hour:13},{quiet_enabled:true,quiet_start:'07:00',quiet_end:'07:00'},{post_times:['25:00']}])assert.throws(()=>validateSchedule({...DEFAULT_SCHEDULE,...bad}));});
test('scheduler bearer and verified admin authorization are distinct; config CAS',async()=>{const env=environment();assert.equal((await req(env,'scheduler/config','GET',undefined,null)).status,403);assert.equal((await req(env,'admin/schedule','GET',undefined,22)).status,403);assert.equal((await req(env,'admin/schedule','GET',undefined,null)).status,401);const first=await req(env,'admin/schedule','GET',undefined,11);assert.equal(first.schedule.post_interval_minutes,10);const saved=await req(env,'admin/schedule','PUT',{schedule:{...first.schedule,post_interval_minutes:30},revision:first.revision},11);assert.ok(saved.revision>first.revision);assert.equal((await req(env,'scheduler/config','PUT',{schedule:first.schedule,revision:first.revision})).status,409);env.db.close();});
test('leases serialize workers; action retries do not overwrite newer request; consume requires lease',async()=>{const env=environment();await req(env,'scheduler/action','POST',{action:'post_now',request_id:'first'});await req(env,'scheduler/action','POST',{action:'post_now',request_id:'second'});assert.equal((await req(env,'scheduler/action','POST',{action:'post_now',request_id:'first'})).post_request,'second');assert.equal((await runtime(env,{op:'consume',kind:'post',request_id:'second',owner:'one'})).ok,false);const locks=await Promise.all(['one','two'].map(owner=>runtime(env,{op:'acquire',kind:'post',owner,ttl:300})));assert.equal(locks.filter(x=>x.ok).length,1);assert.equal((await runtime(env,{op:'renew',kind:'post',owner:'two',ttl:300})).ok,false);assert.equal((await runtime(env,{op:'consume',kind:'post',request_id:'second',owner:'one'})).ok,true);assert.equal((await runtime(env,{op:'consume',kind:'post',request_id:'second',owner:'one'})).ok,false);await runtime(env,{op:'release',kind:'post',owner:'two'});assert.equal((await runtime(env,{op:'acquire',kind:'post',owner:'two'})).ok,false);env.db.close();});
test('claims enforce live owner, gap/caps, seven-day duplicate retention and once-only successful ledger',async()=>{const env=environment(),now=Math.floor(Date.now()/1000);await runtime(env,{op:'acquire',kind:'post',owner:'one'});assert.equal((await runtime(env,{op:'claim',owner:'two',product_id:1})).ok,false);assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:1})).ok,true);assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:1})).ok,false);assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:2})).ok,false);await runtime(env,{op:'complete',owner:'one',product_id:1,success:true});await runtime(env,{op:'complete',owner:'one',product_id:1,success:true});assert.equal((await runtime(env,{op:'snapshot'})).posts.length,1);env.db.prepare('UPDATE scheduler_posts SET ts=?').run(now-400);env.db.prepare('UPDATE scheduler_claims SET ts=?').run(now-400);assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:1})).ok,false);assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:2,max_hour:1})).ok,false);assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:2})).ok,true);await runtime(env,{op:'complete',owner:'one',product_id:2,success:false});env.db.prepare('UPDATE scheduler_claims SET ts=? WHERE pid=2').run(now-400);assert.equal((await runtime(env,{op:'claim',owner:'one',product_id:2})).ok,false);env.db.close();});
test('scan completion and uploaded status persist bounded safe metrics',async()=>{const env=environment();assert.equal((await runtime(env,{op:'scan_complete',owner:'one',new:3})).ok,false);await runtime(env,{op:'acquire',kind:'search',owner:'one'});await runtime(env,{op:'scan_complete',owner:'one',new:3,found:20,added:2,queue_size:100});await runtime(env,{op:'scan_complete',owner:'one',new:2,queue_size:102});const snapshot=await runtime(env,{op:'snapshot'});assert.equal(snapshot.new_today,5);assert.equal(snapshot.queue_size,102);assert.equal(snapshot.scan_running,true);await req(env,'scheduler/status','PUT',{queue_size:102,next_posts:[1,2,3,4,5,6],error:'token=private https://secret.example',password:'never-save'});const admin=await req(env,'admin/schedule','GET',undefined,11);assert.equal(admin.status.password,undefined);assert.equal(admin.status.error.includes('private'),false);assert.equal(admin.status.next_posts.length,5);assert.equal(admin.status.heartbeat_stale,false);env.db.close();});
