CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY, data TEXT NOT NULL, overrides TEXT NOT NULL DEFAULT '{}',
  checked_at INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS products_checked ON products(checked_at DESC);
CREATE TABLE IF NOT EXISTS saved (
  user_id INTEGER NOT NULL, product_id INTEGER NOT NULL, folder TEXT NOT NULL DEFAULT 'Себе',
  owned INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, PRIMARY KEY(user_id,product_id)
);
CREATE TABLE IF NOT EXISTS preferences (user_id INTEGER PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS outfits (
  id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, data TEXT NOT NULL, created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS outfits_user ON outfits(user_id,id DESC);
CREATE TABLE IF NOT EXISTS metadata (key TEXT PRIMARY KEY,value TEXT NOT NULL);
