// Read-only local gallery. Serves only this public report and ten pinned photos;
// never the repository, OAuth config, logs or arbitrary filesystem paths.
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {resolve} from 'node:path';
import {VISUAL_LABELS,visualLabel} from './cloudflare/visual_features.mjs';
const root=process.cwd(),reportPath=resolve(root,'.test-temp/gemma-500-20261010/report.json');
const samples=JSON.parse(readFileSync(resolve(root,'miniapp/cloudflare/visual_staging_samples.json'),'utf8')).products;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const REVIEW={742502965:'Есть белые полосы и логотипы: «однотонный» не описывает весь кроссовок. Не использовать этот признак как подтверждённый для ранжирования.',812988272:'Цвет и форма совпадают с фото. shoulder и crossbody — неоднозначные способы ношения по одному фото; точного соответствия эталону нет.',1023816536:'Цвет, круглые обручи и вставки совпадают. smooth и glossy описывают разные свойства, поэтому расхождение словаря не обязательно означает ошибку по фото.',1113687154:'Ответ был полным JSON,9полей с evidence, finish_reason=stop. Профиль отклонён схемой/словарём и не сохранён. Повторного AI-вызова не было.'};
const photos=new Map();for(const p of samples){const path=resolve(root,`.test-temp/vision-test-20261010/${p.id}.webp`);if(existsSync(path)&&createHash('sha256').update(readFileSync(path)).digest('hex')===p.hash)photos.set(`/photos/${p.id}.webp`,path);}
export function gallery(){
 const r=JSON.parse(readFileSync(reportPath,'utf8'));let correct=0,wrong=0,missing=0,changed=0;
 const cards=samples.map(p=>{const row=r.results.find(x=>x.nmId===p.id),profile=row?.profile,match=profile?.images?.[0]?.hash===p.hash,receipt=r.experiment?.calls_receipts?.find(x=>x.image_hash===p.hash);
  if(profile&&!match)changed++;
  const checks=Object.entries(p.expected).map(([k,v])=>{const got=profile?.fields?.[k]?.value;if(!match||!got){missing++;return `<span class="check unknown">${esc(VISUAL_LABELS[k]||k)}: не подтверждено</span>`;}if(got===v){correct++;return `<span class="check good">✓ ${esc(visualLabel(k+'='+got))}</span>`;}wrong++;return `<span class="check bad">⚠ ${esc(k)}: ${esc(got)} / эталон ${esc(v)}</span>`;}).join('');
  const fields=profile?Object.entries(profile.fields).map(([k,v])=>`<tr><th>${esc(VISUAL_LABELS[k]||k)}</th><td>${esc(visualLabel(k+'='+v.value).split(': ').slice(1).join(': ')||v.value)}${v.hypothesis?' <small>гипотеза</small>':''}<small>Уверенность модели: ${esc(v.confidence)} · не калибрована</small><small>${esc(v.evidence)}</small></td></tr>`).join(''):'';
  return `<article><div class="photo"><img src="/photos/${p.id}.webp" alt="${esc(p.title)}" loading="lazy"></div><div class="details"><div class="eyebrow">WB ${p.id} · ${esc(profile?.group||p.visual_group)}</div><h2>${esc(p.title)}</h2><p class="${profile?'good':'unknown'}">${profile?'Профиль сохранён в staging D1':'Не получен профиль'} · ${row?.cache?'кэш проверен':'кэш не подтверждён'}</p>${REVIEW[p.id]?`<p class="note bad">Проверка по фото: ${esc(REVIEW[p.id])}</p>`:''}<div class="checks">${checks}</div>${profile?`<table>${fields}</table><p class="note">Состав материала и невидимая спинка: ${esc(profile.material)} / ${esc(profile.back_print)}. Не определяем их по рекламе.</p>`:`<p>${esc(row?.error||'Не анализировался')}</p>`}<a href="https://www.wildberries.ru/catalog/${p.id}/detail.aspx" target="_blank" rel="noopener noreferrer">Открыть товар ↗</a><details><summary>Фото и измеренный расход</summary><p>SHA-256: ${esc(profile?.images?.[0]?.hash||p.hash)}</p><p>Neurons: ${esc(profile?.images?.[0]?.usage?.provider_neurons??receipt?.charged??'нет нового вызова')}</p></details></div></article>`;
 }).join('');
 const quality={correct,wrong,missing,reference_total:correct+wrong+missing,changed_images:changed,profiles:r.results.filter(x=>x.profile).length,cache_hits:r.results.filter(x=>x.cache).length,neurons:r.experiment?.charged};
 const html=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vision · проверка реальных фото WB</title><style>:root{font-family:system-ui,sans-serif;color:#182337;background:#f2f5fa}*{box-sizing:border-box}body{margin:0}header,main{max-width:1220px;margin:auto;padding:24px}h1{font-size:clamp(24px,4vw,42px);margin:10px 0}.eyebrow{text-transform:uppercase;letter-spacing:.09em;color:#68778d;font-size:12px}.summary{display:flex;gap:12px;flex-wrap:wrap}.summary div{padding:15px 20px;background:#fff;border-radius:18px}.summary b{display:block;font-size:26px}.note{font-size:13px;color:#647187;line-height:1.6}article{background:#fff;border:1px solid #e4e9f0;border-radius:24px;margin:0 0 24px;overflow:hidden;display:grid;grid-template-columns:minmax(0,40%) minmax(0,60%)}.photo{background:#e9edf3;position:sticky;top:8px;align-self:start}.photo img{display:block;width:100%;max-height:780px;object-fit:contain}.details{padding:26px;min-width:0}h2{margin:8px 0 12px}.good{color:#147047}.bad{color:#a32138}.unknown{color:#637387}.checks{display:flex;gap:6px;flex-wrap:wrap;margin:20px 0}.check{border-radius:12px;padding:7px 10px;background:#f1f5f8;font-size:12px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{border-top:1px solid #edf0f4;padding:12px 0;text-align:left;vertical-align:top}th{width:30%;font-weight:500;padding-right:12px}small{display:block;color:#788599;font-size:11px;margin-top:5px;line-height:1.5}a{color:#3263ce;text-decoration:none}details{margin-top:20px;font-size:12px;overflow-wrap:anywhere}summary{cursor:pointer} @media(max-width:650px){header,main{padding:14px}article{grid-template-columns:1fr;border-radius:18px}.photo{position:static}.photo img{max-height:460px}.details{padding:18px}}</style><header><div class="eyebrow">Изолированный staging · River SHADOW · Production не изменён</div><h1>Фотографии рядом с признаками</h1><p>Gemma 4 26B A4B · настоящий native Workers AI тест, без повторных вызовов Llama.</p><div class="summary"><div><b>${quality.profiles}/10</b>пригодных профилей</div><div><b>${Number(quality.neurons||0).toFixed(4)}</b>Neurons из лимита500</div><div><b>${correct}/${correct+wrong}</b>верных контрольных признаков</div><div><b>${quality.cache_hits}</b>проверенных кэш-повторов</div></div><p class="note">Проверено ${correct+wrong} из ${correct+wrong+missing} контрольных признаков; неизвестных ${missing}. Это небольшой тест, не общая точность модели. Стили — гипотезы, confidence не вероятность правильности. Результаты предыдущего теста не подставлены вместо новых. Ошибки/неизвестные признаки видны отдельно.</p></header><main>${cards}<p class="note">Завершено ${esc(r.finished_at)} · deployment ${esc(r.status?.deployment_id)} · ${esc(r.stop_reason||'завершён без ошибок')}</p></main></html>`;
 return {html,quality};
}
if(process.argv.includes('--serve')){
 createServer((req,res)=>{const path=new URL(req.url,'http://127.0.0.1').pathname;try{if(req.method!=='GET'){res.writeHead(405);return res.end();}if(path==='/'||path==='/index.html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(gallery().html);}if(photos.has(path)){res.writeHead(200,{'Content-Type':'image/webp','Cache-Control':'max-age=3600'});return res.end(readFileSync(photos.get(path)));}res.writeHead(404);res.end('Not found');}catch{res.writeHead(500);res.end('Report unavailable');}}).listen(8771,'127.0.0.1',()=>console.log('GALLERY http://127.0.0.1:8771/; pinned public artifacts only'));
}else{
 const {html,quality}=gallery();let packed=html;for(const [url,path] of photos)packed=packed.replaceAll(url,'data:image/webp;base64,'+readFileSync(path).toString('base64'));writeFileSync(resolve(root,'.test-temp/gemma-500-20261010/gallery.html'),packed);writeFileSync(resolve(root,'.test-temp/gemma-500-20261010/quality.json'),JSON.stringify(quality,null,2));console.log(JSON.stringify(quality));
}
